label_directory: media/adam/ad_dat/corpa/SPEAKER_SEPARATION/humans_libri
ambient_directory: media/adam/ad_dat/corpa/SPEAKER_SEPARATION/ambient
label_size: !!python/tuple [0, 8]
ambient_size: !!python/tuple [0, 2]
label_scale: !!python/tuple [0.5, 1.5]
ambient_scale: !!python/tuple [0.4, 0.6]
duration: 0.15
sr: 8000
snr: !!python/tuple [0, 100]
